name: playgo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.1
  provider: ^6.1.2
  json_annotation: ^4.9.0
  html: ^0.15.4
  flutter_swipe_button: ^2.1.3
  intl: ^0.19.0
  flutter_ringtone_player: ^4.0.0+3
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  path: ^1.9.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2  
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - "assets/goBoard.jpg"
   - 'assets/homeIcon.png'
   - 'assets/mainPage.png'
